### ISSUE TITLE
Inconsistencies in Event time into the round

### ISSUE THREAD

**Issue by kpei** [ibm-dev-incubator/demoparser#8]
Anyone else experiencing this issue?  I'm currently comparing some results against Akiver's CSGO Demo Manager and find that the event times (during a round) are significantly different.  From my knowledge so far, akiver's event time is (Event time in Tick - Freeze Time end Tick)/Server Tick Rate (128).  I am doing this as well on this end but getting times that are a lot lower in general.  Anyone else encounter this issue? 

Example Code:
```
    def on_player_death(event, msg):        
        event_seconds = (demo.current_tick - round_start_tick)/128 # I've verified using demo header that its 128 server tick rate
        print(event_seconds)

    def on_round_freeze_end(event, msg):        
        round_start_tick = demo.current_tick

    demo.add_callback('round_freeze_end', on_round_freeze_end)
    demo.add_callback('player_death', on_player_death)
```

Output on my end:
```
38.3125
45.96875
47.9375 
...
```

Corresponding output from csgo demo manager:
```
0:53
1:00
1:02
...
```

Demo: https://drive.google.com/file/d/1weNEgl6K8uwAF2rATeUDXMUJPpbZfhos/view?usp=sharing

**Comment by rmoe** [comment]
You need to add `global round_start_tick` to `on_round_freeze_end`. Right now it's just declaring a local variable of the same name in that function. Here is the full output of my run of that demo (I've rounded the time in seconds): http://paste.openstack.org/show/731897/. Does that match up with the akiver results?

**Comment by kpei** [comment]
unfortunately it doesnt.  i forgot to say i  simplified my code down to the core issue.  round_start_tick was a class variable testing on my end so that issue of local var wouldnt occur.

the output you get compared to akivers is different and is the same as mine (line 28 to 35)

**Comment by rmoe** [comment]
It's never that easy :)

Is there any way you can dump the actual ticks that the events occur from csgo-demos-manager? It looks like the events are occurring in the correct order and when I take the difference in ticks between the round_start event and the round_freeze_end I get roughly 1920. 1920 ticks is 15 seconds which is the default value of mp_freezetime.
